apiVersion: apps/v1
kind: Deployment
metadata:
  name: coz-deployment
  labels:
    app: coz
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coz
  template:
    # 여기서부터 파드 템플릿이다
    metadata:
      labels:
        app: coz
    spec:
      containers:
      - name: coz-server
        image: sebcontents/cozserver:1.0
        ports:
        - containerPort: 80
    # 여기까지 파드 템플릿이다
